default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: lucianoamalgama
#   host: db
#   username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: myapp_development
test:
  <<: *default
  database: myapp_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>